"""Phase 1 check: does the simulator + a reconstructed legacy controller
reproduce the *shape* of the logged Runs A-E?

    python exp/reproduce_runs.py            # writes report/phase1_numbers.md, figs

Also runs the two sensitivity variants that bear on the unexplained features:
coupling x1.5 and several seeds (latency bursts, d(t)).
"""
import math
import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from ctrl.legacy import LegacyPID  # noqa: E402
from exp import scenarios as S  # noqa: E402
from sim import params as P  # noqa: E402
from sim.config import SimConfig  # noqa: E402
from sim.drive import DriveSafety  # noqa: E402
from sim.engine import simulate  # noqa: E402
from sim.metrics import summarize  # noqa: E402

FIGS = os.path.join(ROOT, "report", "figs")
DEG = 180 / math.pi
SEEDS = (1, 2, 3, 4, 5)


def run_all(base, seed):
    out = {}
    for sc in S.all_runs(base):
        safety = DriveSafety(**S.LEGACY_WATCHDOG)
        log = simulate(sc.cfg, LegacyPID(**S.LEGACY), sc.roll, sc.yaw, seed=seed, safety=safety)
        out[sc.name] = (sc, log, summarize(log))
    return out


def fmt(v, nd=1):
    return "—" if v is None else (f"{v:.{nd}f}" if isinstance(v, float) else str(v))


def table(headers, rows):
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(lines)


def comparison(results_by_seed):
    rows = []
    for name in "ABCDE":
        o = S.OBSERVED[name]
        ss = [r[name][2] for r in results_by_seed]
        med = {k: float(np.median([s[k] for s in ss])) for k in ss[0] if k != "wd_trips"}
        lo = {k: float(np.min([s[k] for s in ss])) for k in med}
        hi = {k: float(np.max([s[k] for s in ss])) for k in med}
        wd = int(np.median([s["wd_trips"] for s in ss]))

        def cell(k, nd=1):
            return f"{med[k]:.{nd}f} [{lo[k]:.{nd}f}–{hi[k]:.{nd}f}]"
        rows.append([name, f"{fmt(o['rms'])} / {cell('rms')}", f"{fmt(o.get('peak'))} / {cell('peak')}",
                     f"{fmt(o.get('mean'))} / {cell('mean')}",
                     f"{fmt(o['i_peak'], 2)} / {med['i_peak']:.2f}",
                     f"{fmt(o.get('clip_pct'), 0)} / {cell('clip_pct', 0)}",
                     f"{int(med['sat_entries'])}", f"{fmt(o.get('wd_trips'))} / {wd}"])
    return table(["Run", "RMS ° obs / sim", "peak ° obs / sim", "mean ° obs / sim",
                  "i peak A obs / sim", "% limited obs / sim", "sat. entries sim",
                  "wd trips obs / sim"], rows)


def plot(res, path, title):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    C1, C2, INK2, GRID = "#2a78d6", "#eb6834", "#52514e", "#e4e3df"
    fig, axes = plt.subplots(5, 2, figsize=(10, 11), sharex=False)
    for row, name in enumerate("ABCDE"):
        sc, log, s = res[name]
        t = log.t
        ax = axes[row, 0]
        ax.plot(t, log.err * DEG, color=C1, lw=1)
        ax.set_ylabel(f"Run {name}\nerror °", color=INK2, fontsize=9)
        o = S.OBSERVED[name]
        ax.text(0.01, 0.95, f"sim RMS {s['rms']:.1f}° / obs {o['rms']}°", transform=ax.transAxes,
                fontsize=8, va="top", color=INK2)
        ax = axes[row, 1]
        ax.plot(t, log.i, color=C2, lw=1, label="motor current")
        ax.plot(t, log.i_lim, color=INK2, lw=1, ls="--", label="limit")
        ax.plot(t, -log.i_lim, color=INK2, lw=1, ls="--")
        clip = log.clipped > 0
        if clip.any():
            ax.fill_between(t, -3.4, 3.4, where=clip, color=C2, alpha=0.12, lw=0,
                            label="command at limit")
        ax.set_ylim(-3.5, 3.5)
        ax.set_ylabel("A", color=INK2, fontsize=9)
        ax.text(0.01, 0.95, f"sim {s['clip_pct']:.0f}% limited / obs {fmt(o.get('clip_pct'), 0)}%",
                transform=ax.transAxes, fontsize=8, va="top", color=INK2)
        if row == 0:
            ax.legend(fontsize=7, frameon=False, loc="lower right", ncol=3)
        for a in axes[row]:
            for sp in ("top", "right"):
                a.spines[sp].set_visible(False)
            a.grid(True, color=GRID, lw=0.6)
            a.tick_params(labelsize=8, colors=INK2)
    axes[-1, 0].set_xlabel("time, s", color=INK2)
    axes[-1, 1].set_xlabel("time, s", color=INK2)
    fig.suptitle(title, x=0.01, ha="left", fontsize=11)
    fig.tight_layout()
    fig.savefig(path, dpi=140)
    plt.close(fig)


def main():
    os.makedirs(FIGS, exist_ok=True)
    out = ["# Phase 1 numbers (generated by exp/reproduce_runs.py)", ""]
    out.append(f"Legacy controller: `{S.LEGACY}`; watchdog 20°/20 ms (log only). "
               f"D/E payload {S.M_PAYLOAD} kg lateral, sweep {S.SWEEP_HZ} Hz. "
               f"Seeds {SEEDS}: median [min–max].\n")

    base = SimConfig()
    nominal = [run_all(base, sd) for sd in SEEDS]
    out += ["## Nominal model (as stated in the brief)", "", comparison(nominal), ""]
    plot(nominal[0], os.path.join(FIGS, "p1_legacy_runs.png"),
         "Legacy PD in the nominal simulator — Runs A–E (seed 1)")

    strong = base.with_(plant=dict(k_yv=P.K_YV * 1.5, k_ya=P.K_YA * 1.5))
    cpl = [run_all(strong, sd) for sd in SEEDS]
    out += ["## Sensitivity: yaw coupling ×1.5", "", comparison(cpl), ""]

    no_burst = base.with_(timing=dict(burst_rate_hz=0.0))
    nb = [run_all(no_burst, sd) for sd in SEEDS[:2]]
    out += ["## Sensitivity: no CAN bursts", "", comparison(nb), ""]

    text = "\n".join(out)
    with open(os.path.join(ROOT, "report", "phase1_numbers.md"), "w") as f:
        f.write(text + "\n")
    print(text)


if __name__ == "__main__":
    main()
